app:
  name: mosting
  port: 8080

db:
  host: localhost
  user: postgres
  password: 12345
  name: golang_gin_frameworks
  port: 5432
  ssl_mode: disable
  timezone: UTC

jwt:
  secret_key: yourSecretKey
